
name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd your-repo || git clone https://github.com/your-username/your-repo.git && cd your-repo
            git pull
            docker build -t myapp .
            docker rm -f myapp || true
            docker run -d -p 80:80 --name myapp myapp
